# nixpacks.toml

[phases.setup]
nixpkgs = [
  "python3Full",     # Includes pip
  "chromium",        # Headless browser
  "chromedriver"     # Selenium driver
]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
